services:
  mongoserver:
    image: mongo
    container_name: mongodb-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - elib-network

  backendapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elib-backend-server
    ports:
      - "8000:8000"
    networks:
      - elib-network
    env_file: .env
    depends_on:
      - mongoserver

networks:
  elib-network:
    driver: bridge
